baseURL: https://dombarter.co.uk/
languageCode: en-gb
title: Dom Barter
theme: "PaperMod"

buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

paginate: 5

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Projects
          url: projects/
        - name: Posts
          url: posts/
        - name: Search
          url: search/

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

params:
  env: "production" # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Dom (Dominic) Barter - Software Engineer"
  author: "Dom Barter"
  mainSections: ["posts", "projects"]
  defaultTheme: auto
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  showtoc: true
  homeInfoParams:
    Title: "Dom Barter - Software Engineer"
    Content: >
      Hi, I'm Dom!

      - I'm a **Junior Software Engineer** studying Computer Science at the University of Sheffield whilst working part-time at [Mina](https://mina.co.uk/).

      - I have a wide range of experience, with nearly 3 years of commerical exposure, across different platforms, languages and frameworks; but I am currently **specialising in C#, .NET and Vue.js** development.

      - If you're looking for more specifics about my education and work experience - my [LinkedIn](https://www.linkedin.com/in/dombarter/) is the best place to look. Otherwise, please have a look around at my different posts and projects and get in touch if you have any questions!
  socialIcons:
    - name: github
      url: "https://github.com/dombarter"
    - name: linkedin
      url: "https://www.linkedin.com/in/dombarter/"
    - name: email
      url: "mailto:dominicbarter@gmail.com"
