name: Hugo GitHub Pages Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Listing Part 1
        run: ls -a
        
      - name: Listing Part 2
        run: ls ./content/posts
        
      - name: Listing Part 3
        run: ls ./public
        
      - name: Listing Part 4
        run: ls ./public/posts

      - name: Build
        run: hugo --minify
        
      - name: Listing Part 1
        run: ls -a
        
      - name: Listing Part 2
        run: ls ./content/posts
        
      - name: Listing Part 3
        run: ls ./public
        
      - name: Listing Part 4
        run: ls ./public/posts

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: dombarter.co.uk
